Milestone2
Ashah15/Bookstore-CMS pull request #2
Opened 2021-06-15 20:46 UTC by Ashah15

initialize the Redux actions, reducers, and store. And define empty React components, separate presentation, and container components.

2021-06-16 01:25 UTC, bellom requested changes
## Hi @Ashah15  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**1. Kindly check out my comments below;**

**2. Kindly update your `README` file**
**Let's make your repo look more professional by updating your `README` file**.
Checkout out the below link for help, feel free to follow this [Microverse template](https://github.com/microverseinc/readme-template) from pathwright

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-06-16 01:25 UTC, bellom commented on src/reducers/initialState.js
> +  { id: 2, title: 'Toonami', category: 'Kids' },
### [Optional]
Kindly be aware that you can use uuidv4 to automatically generate ids. read more 👉 [npm uuid](https://www.npmjs.com/package/uuidv4)

Example:
```
import uuid from 'uuidv4'
id: uuid(): {title: 'Friday 13', category: 'Horror'}
```

2021-06-16 01:25 UTC, bellom commented on src/reducers/initialState.js
> +const initialState = [
According to the instructions on pathwright, I think you need to move this to `src/index.js`

![image](https://user-images.githubusercontent.com/31897434/122143582-a6b8de80-ce49-11eb-86a3-ffbf2e5e22d4.png)

[Pathwright](https://microverse.pathwright.com/library/react-redux-v11/184438/path/step/106376028/)

2021-06-26 08:46 UTC, uche-inyama requested changes
## Changes Required

### Hi Asha Abdulah Hassan :slightly_smiling_face: 

Kindly update your readme, as required from the last review.

### Have a great day :100: 

#### ``` Uchechukwu Henry Inyama ```

2021-06-29 21:41 UTC, taiwo2 approved these changes
# STATUS: APPROVED
@Ashah15  Weldone for implementing the suggestion from previous Code Reviewer. 
Your project is approved kindly make sure your deployment works fine in your next milestone task. Thanks

2021-06-29 21:43 UTC, merged