Milestone5
Ashah15/Bookstore-CMS pull request #5
Opened 2021-07-30 20:39 UTC by Ashah15

Designing specs to build a great UI for the app.

2021-07-30 23:06 UTC, addod19 requested changes
### Hi @Ashah15 , 

Good job so far! Great effort on this project :muscle: 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._
- [ ] It would be better if we improve our PR to give a little detail of the project, for example; the font used, colors, position, flex/grid, etc
- [ ] It would be better if we have a professional README file, REAMDE files serve as documentation for our project, currently, our project does not reflect the README. A professional README must include the following; `title, description of the project, setup instructions, how to clone and run the app locally, live link, authors, etc
- [ ] I  could not review the design of the project because the app returns a `white screen`. I checked the browser console and found a few `syntax errors: unexpected token <`
- [ ] Kindly implement the CSS best practices as outline in the comment under the review


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
No optional comment


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._


__Happy coding__ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-07-30 23:06 UTC, addod19 commented on package.json
>      "stylelint": "^13.13.1",
- [ ] This comment is addressed to the `github/workflows/linters.yml` file but I did not find it in the PR. It would be better if we use the recommended linter files, this is a rule for all Microverse students, it enforces students to write clean code and to follow best practices. Check the recommended file [here](https://github.com/microverseinc/linters-config/blob/master/react-redux/.github/workflows/linters.yml)

2021-07-30 23:06 UTC, addod19 commented on src/components/book.css
> +  line-height: normal;
- [ ] It would be better if we implement the CSS DRY principle in our CSS files, the following rules have been repeated multiple times, hence we can make them better; For example;
```
.someCommonStyle {
  font-stretch: normal;
  font-style: normal;
  line-height: normal;
  letter-spacing: normal;
}
```
Then we apply this style to all the elements with these rules. Doing this will make our code cleaner and easier to maintain

2021-07-30 23:06 UTC, addod19 commented on src/components/book.css
> +  display: flex;
- [ ] It would be better if we implement the CSS DRY principle in our CSS files, the following rules have been repeated multiple times, hence we can make them better; For example;
```
.someCommonStyle {
  display: flex
}
```
Then we apply this style to all the elements with this rule. Doing this will make our code cleaner and easier to maintain

2021-07-30 23:06 UTC, addod19 commented on src/components/book.css
> +  flex-direction: column;
- [ ] It would be better if we implement the CSS DRY principle in our CSS files, the following rules have been repeated multiple times, hence we can make them better; For example;
```
.someCommonStyle {
  flex-direction: column;
}
```
Then we apply this style to all the elements with this rule. Doing this will make our code cleaner and easier to maintain

2021-07-30 23:06 UTC, addod19 commented on src/components/book.css
> +  font-family: RobotoSlab, sans-serif;
- [ ] It would be better if we implement the CSS DRY principle in our CSS files, the following rules have been repeated multiple times, hence we can make them better; For example;
```
.someCommonStyle {
  font-family: RobotoSlab, san-serif;
}
```
Then we apply this style to all the elements with this rule. Doing this will make our code cleaner and easier to maintain

2021-07-30 23:06 UTC, addod19 commented on src/components/book.css
> +tbody {
- [ ] It would be better to style our app with classes, they are efficient and recommended for CSS best practices. For example; we can give a class of `.tbody` and style it appropriately

2021-07-30 23:06 UTC, addod19 commented on src/components/book.css
> +a {
- [ ] It would be better if we use CSS classes for our styling, they are efficient and recommended for CSS best practices. Instead of the `a` element, we can give it a class of `.anchor` and style it appropriately

2021-07-30 23:06 UTC, addod19 commented on src/components/categoryFilter.css
> +nav {
- [ ] It would be better if we use CSS classes for our styling, they are efficient and recommended for CSS best practices. Instead of the `nav` element, we can give it a class of `.anyStyleName` and style it appropriately

2021-07-30 23:06 UTC, addod19 commented on src/components/categoryFilter.css
> +  font-weight: bold;
- [ ] It would be better if we use CSS classes for our styling, they are efficient and recommended for CSS best practices. Instead of the `HTML` element, we can give it a class of `.anyClass` and style it appropriately

2021-07-30 23:06 UTC, addod19 commented on src/containers/bookForm.css
> +#title {
- [ ] It would be better if we use CSS classes for all our styling, they are more efficient compared to the HTML elements and ids.

2021-07-30 23:06 UTC, addod19 commented on src/components/Book.js
> +          {/* <a href="#">Comments</a> */}
- [ ] It would be better if we deleted commented pieces of code, they make our codebase look messy and unprofessional

2021-08-17 21:19 UTC, bellom requested changes
## Hi @Ashah15   :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

# Status: Changes Required! ♻️ 

IMPORTANT: 
Styling is **EXACTLY** the same as the one provided in the designs ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone5/exactlySameAsDesign.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/45791599/))

Project Design:

![image](https://user-images.githubusercontent.com/31897434/80047697-0c3f6280-8506-11ea-9416-a4f1800e2329.png)

Your Project:

![image](https://user-images.githubusercontent.com/31897434/129801636-ca3b2126-5fbc-4a1b-9b98-e7f13f78e4a8.png)

**Heads-Up:  Let's make sure to place the dropdown for category properly;**

Project Design: So once you click categories, the dropdown should appear.

![image](https://user-images.githubusercontent.com/31897434/128144850-4eb83c5b-3ac1-4afd-a767-8b6ee7055458.png)

Another similar example: Here we just need to place the dropdown beside the text `Books`

![image](https://user-images.githubusercontent.com/31897434/128145148-7818df9d-9c04-4720-be7a-a5fc88702ddb.png)
 

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

2021-08-25 22:27 UTC, rukundoeric requested changes
Hi @Ashah15, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] Your app still doesn't look like the provided design. Kindly make sure that Styling is EXACTLY the same as the one provided in the designs ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone5/exactlySameAsDesign.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/45791599/)). Colors, fonts, and layouts must be exactly the same. you can use this[ Color picker](https://chrome.google.com/webstore/detail/colorpick-eyedropper/ohcpnigalekghcmgcdcenkpelffpdolg?utm_source=chrome-ntp-icon) to help you pick up exact colors from the design.

  | Original      | Yours |
  | ----------- | ----------- |
| ![80047697-0c3f6280-8506-11ea-9416-a4f1800e2329](https://user-images.githubusercontent.com/45217364/130871998-88863e2f-c823-4b7b-a5c4-20162973ff21.png) | ![Screen Shot 2021-08-26 at 00 15 40](https://user-images.githubusercontent.com/45217364/130872027-cdae43d6-0780-4302-a891-20e6fda7003a.png) |


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - N/A

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2021-09-08 20:41 UTC, george-shammar requested changes
Hi @Ashah15 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [ ] You've done extremely well with the design so far but to make it complete, please add space (margin) between each book container.  The original design has it and yours doesn't.
- [ ] Also, remove the dark border that you have in the `update progress` button. 

That should do it for the styling.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-10-14 23:47 UTC, eliasecasta approved these changes
## Status:  Approved 🟢

Hi, @Ashah15, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

![](https://media3.giphy.com/media/DnMMGxEvniha7CvASq/giphy.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-27 14:35 UTC, merged